yarnPath: .yarn/releases/yarn-3.6.4.cjs
nmMode: hardlinks-local

nodeLinker: node-modules

# Multi arch needed for github actions on linux. Otherwise it needs to be fetched on every action run.
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
